name: bmbasket
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  splashscreen: ^1.2.0
  carousel_slider: ^2.3.1
  flutter_linkify: ^3.1.3
  flutter_svg: ^0.19.0
  firebase: ^7.3.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.4
  otp_text_field: ^1.0.1
  flutter_form_builder: ^3.14.0
  geolocator: ^6.0.0+4
  geocoding: ^1.0.4+1
  razorpay_flutter: ^1.2.2
  cloud_firestore: ^0.14.0+2
  provider: ^4.3.2+2
  firebase_storage: ^4.0.1
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.3.3
  contactus: ^1.1.7
  geoflutterfire: ^2.2.1
  google_maps_flutter: ^1.0.10
  flutter_range_slider: ^1.5.0
  shared_preferences: ^0.5.3+5
  fancy_shimmer_image: ^1.2.0
  flutter_custom_clippers: ^1.1.2
  fluttertoast: ^7.1.1
  sweetsheet: ^0.2.0
  flutter_spinkit: ^4.1.2+1
  bloc_pattern:
  rxdart:
  eva_icons_flutter: ^2.0.1
  flutter_launcher_icons: "^0.8.0"
  date_picker_timeline: ^1.2.1
  flutter_local_notifications: ^3.0.2
  data_connection_checker: ^0.3.4
  
  badges: ^1.1.6


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcon.jpeg"
  adaptive_icon_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript.ttf
  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/
   - assets/fonts/